name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: true  
  - type: input
    id: browser
    attributes:
      label: Browser Version
      description: "Please provide the full version of the browser that you are using."
      placeholder: "Brave Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)"
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Website
      description: "If the bug occured transforming a specific website, you can provide the link here."
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened and what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell

